micronaut:
  application:
    name: crud
datasources:
  default:
    url: jdbc:postgresql://localhost:5432/example
    driverClassName: org.postgresql.Driver
    username: root
    password: root
    schema-generate: CREATE_DROP
    dialect: POSTGRES

jpa:
  default:
    properties:
      hibernate:
        hbm2ddl:
          auto: update

quantidade:
  elementos: 5

uri:
  scheme: http
  host: localhost
  port: 8080